### ISSUE TITLE
cs_instance -> ssh_key  doesn't work

### ISSUE THREAD

**Issue by stardom3645** [ngine-io/ansible-collection-cloudstack#104]
- ISSUE TYPE
  - Bug Report

- EVN
cloudstack: 4.16
ansible: core 2.12.2
ngine_io.cloudstack: 2.2.4
cs: 3.0.0

- SUMMARY
I tried to deploy instance with ssh_key
but it(using cs module) did not write Public key on "~/.ssh/authorized_keys"
I tested with the same ssh_key with cloudstack(using UI), and it worked well.

Everything seemed fine on Cloudstack but "~/.ssh/authorized_keys" file is empty.
![image](https://user-images.githubusercontent.com/34114265/171134135-62765ffa-95d2-4eed-9674-4c7fd25ef3e2.png)

**Comment by rvalle** [comment]
@stardom3645 please note that when creating an instance you pass the name of the ssh key, then there is another module to create the ssh key in ACS.

**Comment by stardom3645** [comment]
@rvalle  This is the ansible code what i ran.
```
---
- name: Deploy VirtualMachine
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy VirtualMachine
      cs_instance:
        api_url: "{{ API_URL }}"
        api_key: "{{ API_KEY }}"
        api_secret: "{{SECRET_KEY }}"
        zone: Zone
        name: deployed-vm2
        template: centos8.5-0525
        service_offering: 2C-4GB-RBD
        ssh_key: deployed-vm2
        networks:
          - network1
```

Thank you for your sincerity, but the second answer is difficult to understand.
are there any restrictions I should be aware of?
