### ISSUE TITLE
Inventory plugin filter by tags

### ISSUE THREAD

**Issue by martialblog** [ngine-io/ansible-collection-cloudstack#115]
Hi, 

First of all, great collection! Works like a charm. 

I'm having a use case in which I need to filter the instanced by tags.

I quickly hacked something together like this:

```
    def instance_tags_in_filter_tags(self, filter_tags, instance):
        instance_tags = instance.get('tags', [])
        for tag in filter_tags:
            if not tag.items() <= instance_tags.items():
                return False
        return True

    def parse(self, inventory, loader, path, cache=False):
        ...
        for instance in instances:
            filter_tags = self.get_option('filter_by_tags')
            if filter_tags and not self.instance_tags_in_filter_tags(filter_tags, instance):
                continue
```

Maybe not ideal yet, just to prototype the idea.

Before I open a PR, is that something you would consider adding?

Cheers
Markus

**Comment by resmo** [comment]
Hi @martialblog,

So what you already could do is to group instances either by a key or using a group "condition":


```yaml
keyed_groups:
  - key: tags.key
    prefix: tag_key
    separator: ""
groups:
  # add hosts to the group development if any of the dictionary's keys or values is the word 'devel'
  development: "'devel' in (tags|list)"
```

and use them as hosts target in playbooks:

```
- hosts:  tag_key_mykey
```
or

```
- hosts:  development
```

That said, I would be okay in  a "filter by tag" PR (since we already have other filters) .

**Comment by resmo** [comment]
Well, I could probably write a book about "separating tiers" in ansible and cloud environments.

Let's say you have 2 tiers, production, staging which contain instances. One thing you could do is to have a generic playbook for hosts in group "cloud" (so no specified tier)  which contains all cloud hosts:

```
- hosts: cloud
```
and in your playbook run you limit the the hosts to that tier (basically a filter):

```
ansible-playbook cloud.yml --limit grp_staging
```
inventory

```yaml
#...
groups:
  cloud: true
keyed_groups:
  - prefix: grp
    key: tags.groups.split(',')
```
But this can be error prune if you "forget" the `--limit`, the target is a mixed tier of staging and production which can lead to other problems when you have clusters and so forth.

So, my solution is to have separate inventories, cloudstack accounts/projects and API keys per tier:

```
ansible-playbook cloud.yml --inventory ./inventory/staging.cloudstack.yml 
```
you can even "hardcode" then the a group tier 

```yaml
#...
groups:
  cloud: true
```
and put the api key in a `group_vars/staging/somehing.yml` or  `group_vars/staging.yml` resp.  `group_vars/production.yml` for production hosts and because of this separation the hosts returned only consists of the separate projects/account.

I hope this makes sense.
