### ISSUE TITLE
Parameter to specify region when creating a VM instance

### ISSUE THREAD

**Issue by rakesh-p** [ngine-io/ansible-collection-cloudstack#128]
Hi,

Is it possible to specify the region when using ngine_io.cloudstack.cs_instance module please? I am using a cloud provider but   service offering names Iis NOT unique across regions. This means I am not able to create a VM instance using the service offering name. I need to use the service offering ID to make it work.  See below. 

After setting the ENV variables CLOUDSTACK_KEY, CLOUDSTACK_SECRET and CLOUDSTACK_ENDPOINT, I ran the following playbook

**Ansible playbook:**
```
---
- name: Create a CloudStack VM instance
  hosts: localhost
  gather_facts: no
  collections:
    - ngine_io.cloudstack
  tasks:
    - name: Create a VM instance from an existing template
      ngine_io.cloudstack.cs_instance:
        name: ansible-vm-1
        template: ec-rocky-9.4-base
        zone: New York (ESX)
        # service_offering: 2927c1c1-7889-47f9-b987-644cba37618c
        service_offering: 2048-1
        networks:
          - Network Local ECMWF 3
```
Setting service_offering to 2927c1c1-7889-47f9-b987-644cba37618c works well and the VM ius created. But if I change the service_offering value to 2048-1 (which is name of the service offering as per the list serviceoffering output), i get the error that the service offering not found (which is correct because the service offering ID in the error message belongs to another region which does not contain NewYork zone) 

Error: HTTP 431 error 'errortext': 'Unable to execute API command deployvirtualmachine due to invalid value. Invalid parameter serviceofferingid' 

Should this be considered as a feature request to add a region parameter or is there another solution please? 

Thanks

**Comment by rvalle** [comment]
@rakesh-p I think you have to create the offerings per region. I can see that I use the same offering across zones without problems, but I don't think that works across regions. 

luckily you can automate offering creation with cs_service_offering ...

**Comment by resmo** [comment]
Sorry for dump question, I am a bit confused but if I remember correctly, a region has its own api endpoint and keys right? (there aren't any federation yet, right?) 

so wouldn't switching endpoints solve this issue?

```
---
- name: Create a CloudStack VM instance
  hosts: localhost
  gather_facts: no
  collections:
    - ngine_io.cloudstack
  tasks:
    - name: Create a VM instance from an existing template
      ngine_io.cloudstack.cs_instance:
        name: ansible-vm-1
        template: ec-rocky-9.4-base
        zone: New York (ESX)
        # service_offering: 2927c1c1-7889-47f9-b987-644cba37618c
        service_offering: 2048-1
        api_url: "{{ cloudstack_api_url }}"
        api_key: "{{ cloudstack_api_key }}"
        api_secret: "{{ cloudstack_api_secret }}"
        networks:
          - Network Local ECMWF 3
```

usually you organize these vars in `group_vars/region-xyz` and put these instances in the corresponding ansible inventory group in your inventory.
