### ISSUE TITLE
Idenpotency not working with secondary storage proxy global parameter

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#24]
For some reason ansible is reporting that the following:

```
    - name: Configure Secondary Storage Proxy
      cs_configuration:
        name: secstorage.proxy
        value: "{{ lookup('env','http_proxy') }}"
      notify: restart cloudstack-management
```

Is always changing, even when it is not.

Since global parameters require restarting the manager, it is a bit annoying. 

It is strange because other global configuration parameters work as expected.
