### ISSUE TITLE
Picking a particular IP address for a Network

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#30]
When using the UI it is possible to select a particular IP to acquire for a Virtual Network.

I have tried to replicate the same functionality with the cs_ip_address module, but it does not work. The documentation states that the IP address is required for the release functionality, and I guess that it is being ignored on acquisition.

For example, consider 123.123.123.123 a public IP address associated with our ACS account.

The following call:

```
    - name: Assign Public IP to DMZ
      cs_ip_address:
        ip_address: 123.123.123.123
        network: dmz
```

Will assign a random IP form the public pull, but not the requested one.
