### ISSUE TITLE
Cross Zone Template Registration getting warning

### ISSUE THREAD

**Issue by rvalle** [ngine-io/ansible-collection-cloudstack#45]
I am getting a warning for the following snippet:

```
    - name: Wait for Template Registration
      cs_template:
        name: "{{item}}"
        cross_zones: yes
        state: extracted
```

The new warning introduced related to zone:
```
[DEPRECATION WARNING]: Using first zone as default is deprecated because of unreliable API, zone needs to be defined. This feature will be 
```

While it is possible to install a template to a particular zone, I have used the cross-zone option which AFAIR will install in all.

Looks like there seems to be code to stablish the default zone anyway or something and it triggers the warning
