### ISSUE TITLE
IPv6 by default when creating an instance

### ISSUE THREAD

**Issue by John222** [ngine-io/ansible-collection-cloudstack#96]
Hello @resmo 

is it possible to deploy a machine with ```ipv6``` enabled by default? I couldn't find an option to activate it within the ```ngine_io.cloudstack.cs_instance```. Within the exoscale web ui there is a checkbox tick to enable it by default.

**Comment by resmo** [comment]
These modules are primary targeted to apache cloudstack's API.

Exoscale extended the cloudstack API in a custom way. The optional extended custom param would be `ipv6=true` which defaults to `false` (as well as ipv4 which defaults to `true` and is not changeable).

I remember discussing this with exoscale and my suggestion at that time was to use the details param, which is explicitly there to pass additional params,  but I am not sure if this was ever implemented by exoscale.

Could you try:
```yaml
- name: Create VM with IPv6 enabled
  ngine_io.cloudstack.cs_instance:
    name: my VM
    details:
      ipv6: true
    ...

```
